config/routes.rb
Rails.application.routes.draw do

  get 'secrets/index'

  get 'secrets/new'

  get 'sessions/new'

  root 'secrets#index'
  get '/about', to: 'static_pages#home'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/new', to: 'secrets#new'
  post '/new', to: 'secrets#create'
  get '/index', to: 'secrets#index'

  resources :users
  resources :secrets, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/secret.rb
class Secret < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :secrets
  attr_accessor :remember_token
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	                  format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    
  class << self

    # Returns the hash digest of the given string.
  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token

  def new_token
    SecureRandom.urlsafe_base64
  end

  # Persistent sessions

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController

   before_action :logged_in_user, only: [:new, :create]

  def index
  	@secrets = Secret.all
  end

  def new
  	@secret = Secret.new
  end

  def create
    @secret = Secret.new(secret_params)
    @secret.user_id = current_user.id
    @secret.author = current_user.name
  	if @secret.save
  		flash[:success] = "Your secret will be safe with us."
  		redirect_to root_url
  	else
  		flash[:danger] = "Something went wrong."
  		render 'new'
  	end
end

  private


  def logged_in_user
    	unless logged_in? 
    	flash[:danger] = "Members only, please log in"
    	redirect_to login_url
end
end

   private

  def secret_params
  	params.require(:secret).permit(:title, :body)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
  		flash[:success] = "Welcome, you are one of us now!"
  		redirect_to @user
  	else
  		render 'new'
  	end
end

private

def user_params
	params.require(:user).permit(:name, :email, :password,
		                         :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Members Only"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end	
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

	def current_user
	   if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
  end
end

   def forget(user)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

    def logged_in?
      !current_user.nil?
    end

    def log_out
      forget(current_user)	
      session.delete(:user_id)
      @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Members Only App
    by Me
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Members Only", root_path, id: "logo" %>
        <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
     <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/secrets/_secrets.html.erb
<div style="background:transparent !important" class="center jumbotron">
	<h1>Hello strangers!</h1>
	<h2>Feel free to read our secrets.</h2>
	<h2>To better enjoy the experience and get to know the other members we recommend you sign up.</h2>
	<div class="centered">
		<br>
		<%= link_to "Signup", new_user_path, class: "btn btn-lg btn-primary" %>
	</div>
</div>

app/views/secrets/index.html.erb
<% provide(:title, "Secrets") %>
   <h2>Our Secrets</h2>
   
	<div class="row">
	<% if !logged_in? %>
		<%= render 'secrets' %>
	<% end %>
	<div class="col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
		<ul class="secrets">
			<% @secrets.each do |secret| %>
				<li>
					<h4><%= secret.title %></h4>
					<% if logged_in? %> <!-- Only shows the name of the author when the user is logged in -->
						<h5><%= "created by: #{secret.user.name}" %></h5>
					<% end %>
					<p><%= secret.body %></p>
				</li>
			<% end %>
		</ul>
	</div>
</div>

app/views/secrets/new.html.erb
<% provide(:title, "Write Secret") %> <!-- Provides a title to be showcased -->

<h1>Write your secrets</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@secret) do |f| %>

			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
	
			<%= f.label :body %>
			<%= f.text_field :body, class: 'form-control' %>
			<br>
			<%= f.submit "Send", class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
  <p>
  	I'll write something about myself here soon
  </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
  <p>
  	I'll add a contact page here soon
  </p>

app/views/static_pages/home.html.erb
<% provide(:title, "About") %>
<div style="background:transparent !important"class="center jumbotron">
  	<h1>Members Only Site</h1>

  	<h2>
  		This app has been made possible by the fantastic
  		<a href="https://www.theodinproject.com"> Odin Project </a>teachings. I hope to see you there soon!
  	</h2>


  	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
 


<div id="container">
 <div id="floated">
<%= link_to image_tag("members-only.png", alt: "Members Only") %>

</div>
<p>
  		This is the home page for our Members Only website, a place where gossip is encouraged. Non members will be able to read the posts but only members will be authorised to write in here and will know who the other members are.
  	 </p>

  	 <p>
  	 	Gossiping boys are welcome, too!
  	 </p>
</div>
  

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Join now", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>